### PR TITLE
server connections to port 8000 and serves up a static page

### PR DESCRIPTION
**Pull request by dkancalade**
Hey everyone, 

I would like a code review for my server code by whoever has time.  I only need one person.  

There is a bare bones index.html file that is serves to but no react.  

It serves up the index.html on port 8000 fine.

Let me know if you have any suggestions
Thanks.

### CODE REVIEW

**Review by imartinez8 — APPROVED** [review]
Looks good!

**Comment by GalaDev** [comment]
Looks good to me!

**Review by GalaDev — APPROVED** [review]
Looks good to me!

**Review by mervinpan — APPROVED** [review]
I'm not sure if this requires my review to move forward. I thought it just needed 1 person. I just noticed this pop up on my notifications

**Pull request merged**
